### ISSUE TITLE
inserire nel form di creazione le commesse già utilizzate nel mese per poterle selezionare senza aprire l'intero albero

### ISSUE THREAD

**Issue by sandroelmo** [E-ONE-RE/ZETMS_CREATE#14]

**Comment by ppmarco** [comment]
Al momento della creazione di una Entry del timesheet attraverso il form selezionando una commessa esistente compilo automaticamente i campi commessa e sede (NON MODIFICABILI). Compilo inoltre la descrizione, che è modificabile da app.

**Comment by sandroelmo** [comment]
ho creato il bottone di selezione commessa esistente che richiama le commesse già esistenti nel mese. bisogna completare la logica. se l'utente seleziona una commessa già esistente, non andiamo a creare una nuova riga ma facciamo un update della riga del TMSKEY selezionato. Poi ragioniamo sulle spese
