### ISSUE TITLE
gestione modifica commesse già inserite da sistemare

### ISSUE THREAD

**Issue by sandroelmo** [E-ONE-RE/ZETMS_CREATE#75]

**Comment by ppmarco** [comment]
Nella modifica delle commesse:

editing della spesa: disattivare bottoni di modifica e di eliminazione commessa.
salvataggio della spesa: riattivazione bottoni.
pressione bottone di edit ---> modifica della spesa (ma non salvataggio) ---> pressione pulsante di editing: resettare il campo importo e descrizione.
